import type { Route } from "./+types/analysis-records";
import { getEnvContext } from "~/context";
import {
  createAnalysisRecord,
  getLatestAnalysisRecords,
} from "~/features/analysis-team/api/handlers";
import { insertAnalysisRecordSchema } from "~/features/analysis-team/database/schema";

function getDeps(context: Route.LoaderArgs["context"]) {
  const { db } = getEnvContext(context);
  return { db };
}

/**
 * GET /api/v1/analysis-records
 *
 * Get latest analysis records, sorted by time from newest to oldest
 * Supports both regular pagination (limit) and grouped pagination (grouped=true)
 *
 * Query Parameters:
 * - traderId: string (optional) - Filter analysis records for specific trader
 * - limit: number (optional, default: 20, max: 100) - Number of records to return (or groups if grouped=true)
 * - cursor: string (optional) - ISO timestamp for cursor-based pagination (used with grouped=true)
 * - grouped: boolean (optional, default: false) - If true, returns grouped by recordId with pagination support
 *
 * Response (grouped=false):
 * {
 *   success: true,
 *   data: AnalysisRecord[]
 * }
 *
 * Response (grouped=true):
 * {
 *   success: true,
 *   data: {
 *     groups: Array<{
 *       key: string;
 *       recordId: string | null;
 *       records: AnalysisRecord[];
 *       latest: string;
 *       traderId: string;
 *       traderName: string | null;
 *     }>;
 *     nextCursor: string | null;
 *   }
 * }
 */
export async function loader({ request, context }: Route.LoaderArgs) {
  const { db } = getDeps(context);
  const url = new URL(request.url);

  // Parse query parameters
  const traderId = url.searchParams.get("traderId") || undefined;
  const limitParam = url.searchParams.get("limit");
  const cursor = url.searchParams.get("cursor") || undefined;
  const grouped = url.searchParams.get("grouped") === "true";

  let limit = grouped ? 10 : 20; // Default: 10 groups or 20 records

  if (limitParam) {
    const parsedLimit = Number(limitParam);
    if (isNaN(parsedLimit) || parsedLimit < 1) {
      return Response.json(
        {
          success: false,
          error: "Invalid limit parameter",
        },
        { status: 400 }
      );
    }
    limit = Math.min(parsedLimit, grouped ? 50 : 100); // Max 50 groups or 100 records
  }

  try {
    if (grouped) {
      const { getLatestAnalysisGroups } = await import(
        "~/features/analysis-team/api/handlers"
      );
      const result = await getLatestAnalysisGroups(db, {
        traderId,
        limit,
        cursor,
      });

      return Response.json({
        success: true,
        data: result,
      });
    } else {
      const records = await getLatestAnalysisRecords(db, { traderId, limit });

      return Response.json({
        success: true,
        data: records,
      });
    }
  } catch (error) {
    console.error("Error fetching latest analysis records:", error);
    return Response.json(
      {
        success: false,
        error: "Failed to fetch latest analysis records",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

export async function action({ request, context }: Route.ActionArgs) {
  // Authentication
  // const authResult = await authenticate(request, context);
  // if (!authResult.success) {
  //   return Response.json(
  //     {
  //       success: false,
  //       error: authResult.error?.message ?? "Unauthorized",
  //       code: authResult.error?.code ?? "UNAUTHORIZED",
  //     },
  //     { status: 401 }
  //   );
  // }

  // setUserContext(context, authResult.user);

  // Only handle POST requests
  if (request.method !== "POST") {
    return Response.json(
      {
        success: false,
        error: "Method not allowed",
        code: "METHOD_NOT_ALLOWED",
      },
      { status: 405 }
    );
  }

  const deps = getDeps(context);

  try {
    // Parse request body
    const body = (await request.json()) as Record<string, unknown>;

    // Validate data
    const validationResult = insertAnalysisRecordSchema.safeParse({
      ...body,
      id: undefined, // id is auto-generated by database
      createdAt: body.createdAt || undefined, // Optional, uses database default
      updatedAt: undefined, // Auto-updated by database
    });

    if (!validationResult.success) {
      return Response.json(
        {
          success: false,
          error: "Invalid request data",
          code: "VALIDATION_ERROR",
          details: validationResult.error.flatten(),
        },
        { status: 400 }
      );
    }

    // Create analysis record
    const record = await createAnalysisRecord(deps.db, {
      traderId: validationResult.data.traderId,
      role: validationResult.data.role,
      chat: validationResult.data.chat,
      jsonValue: validationResult.data.jsonValue ?? undefined,
      recordId: validationResult.data.recordId ?? undefined,
      createdAt: validationResult.data.createdAt ?? undefined,
    });

    return Response.json(
      {
        success: true,
        data: record,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Failed to create analysis record:", error);
    return Response.json(
      {
        success: false,
        error:
          error instanceof Error ? error.message : "Failed to create analysis record",
        code: "CREATE_FAILED",
      },
      { status: 500 }
    );
  }
}
